name: Build Windows Release
on:
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    name: Build for winOS-x64
    runs-on: windows-latest
    steps:
      - name: Get Current Date
        id: current_date
        run: |
          $CURRENT_DATE=& Get-Date -format yyyy.MM.dd
          echo "CURRENT_DATE=$CURRENT_DATE" >> $env:GITHUB_ENV

      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Prepare Visual Studio
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.3.224.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
          vulkan-use-cache: true

      - name: Prepare Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Prepare CMake
        uses: lukka/get-cmake@latest

      - name: Configure CMake Build Location
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: |
          cmake -G "Visual Studio 17 2022" -A x64
          cmake --build ${{github.workspace}}/build --config Release

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Sumi-x64.zip'
          directory: '${{ github.workspace }}/build'
          path: '${{ github.workspace }}/build/bin/Release'
          exclusions: 'tests.exe'
          recursive_exclusions: tests.exe

      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: ${{ env.CURRENT_DATE }}.${{ github.run_number }}
          artifacts: "${{ github.workspace }}/build/*.zip"
          tag: ${{ env.CURRENT_DATE }}.${{ github.run_number }}
          commit: master
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
